name: zip
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.11
    branches:
      - main

env:
  VERSION: 1.0.0
  MINECRAFT_VERSION: 1.21-1.21.10
  NOTES: |
    - Initialized project
    - Added supported_formats field
    - Updated min_format and max_format to 88 (1.21.10)
    - Other minor changes

jobs:
  zip-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 🤐 Zip
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: /
          dest: AFK Check v${{ env.VERSION }} ${{ env.MINECRAFT_VERSION }}.zip
      - name: 🏷️ Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ env.VERSION }}_${{ env.MINECRAFT_VERSION }}" -m "AFK Check v${{ env.VERSION }} ${{ env.MINECRAFT_VERSION }}"
          git push origin "v${{ env.VERSION }} ${{ env.MINECRAFT_VERSION }}"
      - name: 🫸Create Release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: 'v${{ github.run_number }}'
            release_name: 'AFK Check v${{ github.run_number }}'
            body: '${{ env.NOTES }}'